#cloud-config
# vim: syntax=yaml
users:
  - name: vesop
    shell: /bin/bash
    plain_text_passwd: Volterra123
    lock_passwd: false
    no_create_home: true
    no_user_group: true
runcmd:
  - mkdir -p /usr/local/var/run
  - wget https://github.com/alexgit2k/qemu-guest-agent-static/raw/master/qemu-ga-static-3.1.0-1.x86_64.rpm -O /root/qemu-ga-static-3.1.0-1.x86_64.rpm
  - cd / && rpm2cpio /root/qemu-ga-static-3.1.0-1.x86_64.rpm | cpio -idmv
  - ln -s /etc/init.d/qemu-ga /etc/rc3.d/S20qemu-ga
  - # /etc/init.d/qemu-ga start

